repos:
  - repo: local
    hooks:
      - id: check-catalog-version
        name: catalog_version muss "main" sein auf Branch main
        language: script
        entry: .hooks/check_catalog_version.sh
        pass_filenames: false
        always_run: true

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.0
    hooks:
      - id: gitleaks

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.30
    hooks:
      - id: tofu-fmt
      # - id: tofu-validate
      # - id: goimports
