#!/usr/bin/env bash

#MISE description "Apply a Terragrunt stack"
#USAGE arg "<target>" help="The target unit" default=""
#USAGE flag "-d --dry-run" help="Show the commands without executing it"
#USAGE flag "-y --yes" help="Automatic yes to prompts" default="false"

#MISE raw=true

set -e

source "$MISE_CONFIG_ROOT/.mise/common.sh"

STACKS_DIR="$MISE_CONFIG_ROOT/examples/terragrunt/stacks"

if [[ -z "${usage_target:-}" ]]; then
  stack_dirs=()

  while IFS= read -r -d '' dir; do
    stack_dirs+=("$(basename "$dir")")
  done < <(find "$STACKS_DIR" -mindepth 1 -maxdepth 1 -type d -print0)

  selected_stack=$(printf "%s\n" "${stack_dirs[@]}" | gum choose --header="Select a stack to operate on:")
else
  selected_stack+=("${usage_target}")
fi

cd "$STACKS_DIR/$selected_stack"

CMD="terragrunt stack run apply"

if [ "${usage_yes?}" = "true" ]; then
  CMD+=" --non-interactive"
fi

logCommand "$CMD" "$usage_dry_run"

eval $CMD
