#! /usr/bin/env bash

set -e

#USAGE flag "-t --tofu" help="Run tofu tests"
#USAGE flag "-u --units" help="Run terragrunt unit tests"
#USAGE flag "-s --stacks" help="Run terragrunt stack tests"
#USAGE flag "-a --all" help="Run all tests"

if [ "$usage_all" != "true" ] && [ "$usage_tofu" != "true" ] && [ "$usage_units" != "true" ] && [ "$usage_stacks" != "true" ]; then
  echo ""
  echo -e "No test type specified. \nUse -a, -t, -u, or -s to specify tests to run."
  echo ""

  exit 1
fi

TOFUS=(
  # naming
  # proxmox-pool
  # proxmox-vm
  # proxmox-lxc
  # dns
  netbox
)

UNITS=(
  # naming
  # proxmox-pool
  # proxmox-vm
  # proxmox-lxc
  # dns
  # dns-wildcard
  netbox
)

STACKS=(
  # homelab-proxmox-pool
  # homelab-proxmox-container
  # homelab-proxmox-vm
  # homelab-wildcard-dns
  homelab-netbox
)

mise run terragrunt:cleanup

# === TOFU ===
function run_tofu_tests() {
  for TOFU in "${TOFUS[@]}"; do
    mise run tofu:init $TOFU
    sleep 1
    mise run tofu:plan $TOFU
    sleep 1
    mise run tofu:apply $TOFU
    sleep 1
  done

  for (( idx=${#TOFUS[@]}-1 ; idx>=0 ; idx-- )); do
    TOFU="${TOFUS[idx]}"
    mise run tofu:destroy $TOFU -a
    sleep 1
  done
}

# === TERRAGRUNT UNITS ===
function run_terragrunt_unit_tests() {
  for UNIT in "${UNITS[@]}"; do
    # mise run terragrunt:unit:plan $UNIT
    # sleep 1
    mise run terragrunt:unit:apply $UNIT
    sleep 1
  done

  # Destroy in reverse order
  for (( idx=${#UNITS[@]}-1 ; idx>=0 ; idx-- )); do
    UNIT="${UNITS[idx]}"
    mise run terragrunt:unit:destroy $UNIT -a
    sleep 1
  done
}

# === TERRAGRUNT STACKS ===
function run_terragrunt_stack_tests() {
  # check latest changes to git are commited and pushed and fail with a message if not
  # GIT_STATUS=$(git status --porcelain)

  # if [ -n "$GIT_STATUS" ]; then
  #   echo "❌ There are uncommitted changes in the repository. Please commit and push all changes before running stack tests."
  #   exit 1
  # fi

  for STACK in "${STACKS[@]}"; do
    # mise run terragrunt:stack:plan $STACK
    # sleep 1
    mise run terragrunt:stack:apply $STACK -a
    sleep 1
  done

  # Destroy in reverse order
  for (( idx=${#STACKS[@]}-1 ; idx>=0 ; idx-- )); do
    STACK="${STACKS[idx]}"
    # mise run terragrunt:stack:destroy $STACK -a
    sleep 1
  done
}

# === main ===

if [ "$usage_all" = "true" ] || [ "$usage_tofu" = "true" ]; then
  echo "=== Running TOFU tests ==="
  run_tofu_tests
fi
if [ "$usage_all" = "true" ] || [ "$usage_units" = "true" ]; then
  echo "=== Running Terragrunt Unit tests ==="
  run_terragrunt_unit_tests
fi
if [ "$usage_all" = "true" ] || [ "$usage_stacks" = "true" ]; then
  echo "=== Running Terragrunt Stack tests ==="
  run_terragrunt_stack_tests
fi

echo "✅ All tests completed successfully."
