#!/usr/bin/env bash

#MISE description "Initialize a Tofu unit"
#USAGE arg "<target>" help="The target unit" default=""
#USAGE flag "-d --dry-run" help="Show the commands without executing it"

#MISE raw=true

set -e

source "$MISE_CONFIG_ROOT/.mise/common.sh"

TOFU_DIR="$MISE_CONFIG_ROOT/examples/tofu"

if [[ -z "${usage_target:-}" ]]; then
  module_dirs=()

  while IFS= read -r -d '' dir; do
    module_dirs+=("$(basename "$dir")")
  done < <(find "$TOFU_DIR" -mindepth 1 -maxdepth 1 -type d -print0)

  selected_module=$(printf "%s\n" "${module_dirs[@]}" | gum choose --header="Select a unit to operate on:")
else
  selected_module+=("${usage_target}")
fi

cd "$TOFU_DIR/$selected_module"

CMD="tofu init"

logCommand "$CMD" "$usage_dry_run"

eval $CMD
