#!/usr/bin/env bash

#MISE description "Destroy a Terragrunt unit"
#USAGE arg "<target>" help="The target unit" default=""
#USAGE flag "-d --dry-run" help="Show the commands without executing it"
#USAGE flag "-y --yes" help="Automatic yes to prompts" default="false"

#MISE raw=true

set -e

UNITS_DIR="$MISE_CONFIG_ROOT/examples/terragrunt/units"

if [[ -z "${usage_target:-}" ]]; then
  unit_dirs=()

  while IFS= read -r -d '' dir; do
    unit_dirs+=("$(basename "$dir")")
  done < <(find "$UNITS_DIR" -mindepth 1 -maxdepth 1 -type d -print0)

  selected_unit=$(printf "%s\n" "${unit_dirs[@]}" | gum choose --header="Select a unit to operate on:")
else
  selected_unit+=("${usage_target}")
fi

cd "$UNITS_DIR/$selected_unit"

CMD="terragrunt destroy"

if [ "${usage_yes?}" = "true" ]; then
  CMD+=" -auto-approve"
fi

echo ""
echo "🚀 Executing..."
echo "   Command: $CMD"
echo "   Working dir: $(pwd)"
echo ""

if [ "$usage_dry_run" = "true" ]; then
  echo "Dry run mode. Command not executed."
  exit 0
fi

eval $CMD
